[package]
name = "sqlast"
version = "0.0.0"
authors = ["Mobikit <mobikit.io>"]
edition = "2018"
description = "SQL parsing and composing"
license     = "none"

[dependencies]
sqlparser = { version = "0.6.1", features = ["serde"] }
serde_json = { version = "1.0"}
