[package]
name = "sqlast"
version = "0.1.0"
authors = ["user"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
sqlparser = { version = "0.6.1", features = ["serde"] }
serde_json = { version = "1.0"}
